info:
  application:
    name: Gugultaş
    description: Eleştirilere açık , özgün fikirlere sahip ve kalemi keskin olan her vatandaşımızı dergimize davet ediyoruz..
    author: goldeneagle3
    version: '@project.version@'
spring:
  profiles:
    active: ${PROFILE}
